test_linux:
  container:
    image: node:latest

  test_script:
  - npm install --global --unsafe-perm=true esy
  - esy install
  - esy build

test_windows:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019

  test_script:
  - npm install --global --unsafe-perm=true esy

test_macos:
  osx_instance:
    image: mojave-base

  task:
    test_script:
    - npm install --global --unsafe-perm=true esy

publish:
  only_if: $BRANCH == "master"
  depends_on:
    - test_linux
    - test_macos
    - test_windows

  publish_script:
  - echo ok
