task:
  name: test_linux
  container:
    image: node:latest

  test_script:
  - npm install --global --unsafe-perm=true esy
  - esy install
  - esy build

task:
  name: test_macos
  osx_instance:
    image: mojave-base

  test_script:
  - npm install --global --unsafe-perm=true esy

task:
  name: test_windows
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019

  test_script:
  - npm install --global --unsafe-perm=true esy

task:
  name: publish
  container:
    image: node:latest
  only_if: $BRANCH == "master"
  depends_on:
    - test_linux
    - test_macos
    - test_windows

  publish_script:
  - echo ok
